polyml/polyml

polyc.in
As discussed on the mailing list, it would be useful to allow building of interactive heaps as a series of deltas over the base `poly` executable.  With this patch, this could be done.  (Though `PolyML.SaveState` might achieve all I need in any case.)
=> Allow polyc to specify base compiler with -b switch

libpolyml/x86asm.asm
GNU as marks the stack as executable by default unless told otherwise, which this patch does. Tested under Linux (it compiles and runs `fun id x = x; id "foo";` in the interpreter). I don't have access to a Windows machine to test, but I'm hoping I got everything right so that MASM just skips over it.
=> Stop the stack being made executable under Linux

configure.ac, libpolyml/elfexport.cpp, libpolyml/elfexport.h, libpolyml/exporter.cpp, libpolyml/x86_dep.cpp
this patche make it possible to use polyml under x86-64 OpenBSD. Main differences are the elf_abi.h header and sigcontext. As a caveat, this does require a configure script refresh.
=> Compile in x86-64 OpenBSD.

libpolyml/gc_mark_phase.cpp
The loop counter was never actually used, so it kept clearing entry 0. This makes it clear every entry.
=> Fixed duplicated typo stopping the LOC from being reset

basis/Foreign.sml
When a SML vector/array is passed using cVectorPointer or cArrayPointer,
each elements are stored on wrong memory addresses.
=> Fix calculate offset addr using sizeof element

Makefile.am
The check rule is conventionally used for running test suites, and automake likes to adhere to this convention. Like many of the other rules, it has an auto-generated check rule based on the contents of various macros, but also a check-local rule for defining custom tests, which check has as a prerequisite.
=> Use conventional check rule in Makefile for running test suite

config.h.in, configure.ac, winconfig.h
Little-endian MIPS is identified by mipsel, so this makes the configure script treat mips* as MIPS. I have also included a couple of cleanup commits; I don't know if these are desired, so I can remove them from the pull request (or alter them) if you would like. The current `configure` is outdated compared to `configure.ac`, and so will need to be regenerated.
=> Add support for little-endian MIPS

libpolyml/unix_specific.cpp
Fixes narrowing conversion inside braces on PowerPC with GCC 6. NOFLSH is 0x80000000u on PowerPC, but sizeof(int) is 4, so casting to an int is a narrowing conversion and leads to a negative entry. I don't know whether the negative entry itself is harmless, but with GCC 6 defaulting to C++11, narrowing conversions inside `{ }` are errors, so it fails to compile.
=> Define unixConstVec as unsigned

libpolyml/elfexport.cpp
Fixes ld warning about linking abicalls files with non-abicalls files
=> Mark polyexport.o as CPIC on MIPS when code is position-independent

libpolyml/basicio.cpp, libpolyml/bitmap.cpp, libpolyml/foreign.cpp, libpolyml/memmgr.cpp, libpolyml/polyffi.cpp, libpolyml/processes.cpp, libpolyml/sharedata.cpp
This PR contains some trivial changes that do some clean up and remove some compiler warnings. I haven't contributed to Poly/ML before, so if my changes are unacceptable or in a suboptimal format, please let me know and I can adjust them. Thanks for your time.
----
I was also going to change patterns like `malloc` then `memset 0` into a call to `calloc` in situations like in bitmap.cpp. A single call to `calloc` has the potential to be slightly faster, though I would not necessarily expect it to make a noticeable difference to macro benchmarks. Please let me know if you'd like me to include that in this PR or if you'd prefer not to make this change. Thanks!
=> Various trivial tweaks.

libpolyml/savestate.cpp
This PR removes unused members from the save state structs, reducing the size of exported heaps, though admittedly not by a great amount. I was also considering re-arranging the struct members to more tightly pack them (e.g. `unsigned` is 4 bytes on x86_64 which leaves an intermediate 4 bytes of unused padding in between a lone `unsigned` and a following 8 byte member).
Thanks for merging my last PR, and I realise this is a much more controversial change. My thinking is essentially to avoid repeatedly writing this unused (zeroed) data and minimise saved heap sizes in any way possible. My overall motivation is reducing the size of heaps generated by Isabelle/HOL. I realise this change alone has very little impact on the total heap size, but it seemed like clear low hanging fruit to me.
=> Shrink the on-disk size of headers in saved states

libpolyml/bitmap.cpp, libpolyml/elfexport.cpp, libpolyml/machoexport.cpp, libpolyml/pecoffexport.cpp, libpolyml/polyffi.cpp, libpolyml/processes.cpp, libpolyml/sighandler.cpp, libpolyml/statistics.cpp
This PR uses `calloc` or explicit array initialisation to avoid some calls to `memset`, with the aim of potential performance improvements and code clarification. Note that some of these changes do touch performance critical code (e.g. bitmap.cpp).
These changes pass the test suite, but I'm aware that the test suite does not exercise some of the affected code. I also have only x86_64 Linux machines to test on. If you have a more in-depth way of validating these changes, please let me know and I can run further tests.
=> Avoid some calls to memset.

config.h.in, configure.ac, libpolyml/elfexport.cpp
Unfortunately, for the test suite to pass, I have to patch glibc to avoid https://sourceware.org/bugzilla/show_bug.cgi?id=19741, as otherwise calls to `gethostbyname` lead to an assertion failure within glibc. It may be that some systems don't run into this and get lucky with pointer alignment, but the one I was using consistently crashed without patching glibc to weaken the failing assertion.
=> Add support for Motorola 68000

basis/FinalPolyML.sml, libpolyml/elfexport.cpp, libpolyml/machoexport.cpp, libpolyml/pecoffexport.cpp, libpolyml/pexport.cpp, libpolyml/savestate.cpp, libpolyml/timing.cpp, libpolyml/timing.h
Reproducibility was tested on Debian using [prebuilder](https://anonscm.debian.org/cgit/reproducible/misc.git/tree/prebuilder/?id=420424b096c254aa5610b479fb1746e1a7bd13cb), which performs two builds with different locales, file timestamps and timezones. The resulting binaries were bit-for-bit identical. The ioarea changes have been tested on Windows (native and interpreted x64), OS X and Debian GNU/Linux (native and interpreted amd64; interpreted armhf), which covers all three exporters.
=> Make build reproducible

PolyML.exe.manifest, PolyML/PolyML.vcxproj
This makes Windows style the dialog boxes to look modern, rather than using the old plain grey look.
=> Enable Visual Styles for Windows GUI

libpolyml/basicio.cpp, libpolyml/exporter.cpp, libpolyml/polystring.cpp, libpolyml/polystring.h, libpolyml/savestate.cpp, libpolyml/statistics.cpp
Systems are not required to define PATH_MAX/MAXPATHLEN if there is no limit, and in fact the Hurd does not define PATH_MAX/MAXPATHLEN; by removing all of these uses, it now builds on the Hurd.
=> Remove all use of MAXPATHLEN and its variants

config.h.in, configure.ac, libpolyml/x86asm.asm
This allows the stack to be marked as non-executable on the Hurd and Debian GNU/kFreeBSD.
=> Mark stack as non-executable on all GNU systems

config.h.in, configure.ac, libpolyml/elfexport.cpp, libpolyml/quick_gc.cpp, libpolyml/realconv.cpp
This is a 32-bit ABI for amd64, allowing the compiler to use the extended set of registers on an amd64 processor, whilst using 32-bit pointers and words for reduced memory usage. Currently only the interpreted version is supported.
=> Add support for x32 ABI

libpolyml/unix_specific.cpp
On some platforms, such as the Hurd, NOFLSH is `1 << 31`. If the system is 32-bit (like the Hurd currently), this is a negative signed value (as 1 is a signed constant).
=> Cast NOFLSH to unsigned

documentation/Reference/PolyMLMake.html
`suffixes` function has moved to PolyML structure rather than the Compiler. Updated doc.
=> update doc with correct function ref.

config.h.in, configure.ac, libpolyml/elfexport.cpp, libpolyml/reals.cpp
Passes the test suite. SuperH only has two rounding modes, `FE_TONEAREST` and `FE_TOWARDZERO`, with `FE_UPWARD` and `FE_DOWNWARD` not defined.
=> Add support for SuperH

libpolyml/savestate.cpp
This commit modifies the state loading logic to return when file operations
fail while processing relocations. The rationale is that, while it may make
sense to continue when a relocation entry is corrupted, is does not make sense
to continue when an fread or fseek fails as we end up incorrectly interpreting
data.
=> libpolyml: Bail out when file operations fail during state loading.

libpolyml/processes.h
HAVE_PTHREAD isn't necessarily defined when processes.h is included, as it is defined in processes.cpp, but not when included by interpret.cpp.  As a result, the root thread can believe that an interrupted thread has been killed, prematurely deleting its task data. This fixes #9.
=> Fix threadExited and interrupt_requested overlapping

libpolyml/arb.cpp
This caused Tests/Succeed/Test101.ML to fail on big-endian systems if compiled with GMP support, as the limbs are stored in little-endian order, but not the bytes within the limbs themselves. I'm also slightly wary of logical_long, as it uses byte arrays and does two's complement in places, so that might need checking as well (and a test case, of course, if it turns out to be broken!).
=> Fix get_arbitrary_precision_as_real with GMP on big-endian systems

polyc.in
This stops polyc from setting (and potentially shadowing) the implicit it variable, allowing Tests/Fail/Test071.ML to pass when the test suite is compiled with polyc.
=> Don't set "it" in polyc

libpolyml/bitmap.cpp
Given this is internal functionality, I wasn't sure how to evaluate this in place so I ran the following code:
```c
#include "bitmap.h"
using namespace std;
int main(void) {
for (unsigned i = 0; i < 1024; i++) {
for (unsigned j = 1; j < 4096; j++) {
Bitmap b;
b.Create(8192);
b.SetBits(i, j);
}
}
return 0;
}
```
A fairly coarse grained evaluation, but running with the old version of bitmap.cpp on x86_64 I get:
```bash
$ time ./a.out
./a.out  1.88s user 0.00s system 99% cpu 1.882 total
```
and then after applying these changes:
```bash
$ time ./a.out
./a.out  0.40s user 0.00s system 98% cpu 0.400 total
```
To me, this change looks safely portable and should be as fast or faster on all architectures, but I don't have any others available to test. Please let me know if you think this will not …
=> Optimise a loop in Bitmap::SetBits.

modules/IntInfAsInt/Makefile.am, modules/IntInfAsInt/Makefile.in
The file name was being appended to `-c` in `$(INSTALL_PROGRAM)`, resulting in it being treated as some invalid options and causing `make install` to fail.
=> Fix installation error

configure.ac, libpolyml/Makefile.am, libpolyml/poly_specific.cpp, libpolyml/version.h
The patches themselves are (hopefully) fairly self-explanatory. Regarding the -DFOO= + Xstr(FOO) uses, this is a minimal fix, but is there a reason why config.h can't be used for them like everything else?
=> Fix MODULEDIR on Linux and wrong TextVersion

libpolyml/elfexport.cpp, libpolyml/elfexport.h
As discussed via email, this refactors elfexport to use preprocessor defines rather than member variables for directReloc and useRela. It also fixes the ELF ABI on HPPA Linux and NetBSD, and uses the right relocations for function pointers on HPPA and IA-64.
I don't have access to an IA-64 machine (though I may be able to find someone who does), and the HPPA machine I would use is currently offline, so I haven't actually tested those parts of the patch.
=> Refactor elfexport and fix HPPA/IA-64

modules/IntInfAsInt/Makefile.am, modules/IntInfAsInt/Makefile.in
`INSTALL_PROGRAM` makes the installed file executable, but modules don't need to be, so should be installed as data instead (but still with `install-exec-local` as they're platform-specific and in a subdirectory of `libdir`).
=> Install built modules as data rather than executables

libpolyml/pexport.cpp, libpolyml/pexport.h
This patch series does three things:
1. use a `size_t` for indexing an array instead of `unsigned`;
2. use a `std::vector` instead of `calloc` for an array in `PExport::exportStore`; and
3. remove persistence of `indexOrder` as a member variable of `PExport`.
The test suite does not appear to exercise this code and I don't have a good way of testing these changes, but this seems like a move in the right direction to me (less manual memory management, smaller scope of memory allocations). Just wanted to post this to see what you think. As I said, I haven't tested this so please don't assume it works it works as-is. Thanks as always.
=> [RFC] Replace remaining memory management in PExport::exportStore

libpolyml/savestate.cpp
Other memory allocations in this function anticipate failure and call
raise_syscall, but this one was not.
=> fix unchecked malloc in ShowParent

libpolyml/xwindows.cpp
The macro raise_syscall was being used in this instance as if it took a
printf-style format argument, when in actual fact it does not.
Closes #93.
=> remove %d from non-format string

libpolyml/check_objects.cpp, libpolyml/gc.cpp, libpolyml/memmgr.cpp, libpolyml/quick_gc.cpp, libpolyml/sharedata.cpp
When teaching compilers that `Crash`, `Log` and `Exit` are printf-like (with
`__attribute__((format(printf...)))`) they note that we are calling these
functions with format specifiers that are of different widths and/or signs than
their corresponding arguments in some cases. This commit fixes all such
instances.
The `zu` specifier that I've used in a couple of places is only supported in more recent compilers (e.g. VS < 2013 did not support it) but I'm assuming it's fine to use as it's already in other places in the code base. Nevertheless it might be worth getting anyone who uses older compilers to test this patch.
=> fix some specifiers in formatting strings

libpolyml/processes.cpp
Instead of manually managing memory for the `taskArray`, we now use a
`std::vector<TaskData*>` that we expand as necessary. This commit also removes a
case where we were accidentally releasing the scheduler lock twice on an
allocation failure.
Closes #94.
----
I ran the test suite, but I suspect it doesn't exercise this code so any other suggestions on how to validate these changes?
Also, while running the test suite I found Succeed/Test082.ML fails for me because the connection attempt returns `ETIMEDOUT`. This seems like a legitimate error for this scenario, isn't it? This is on a MacOS machine, `uname -rsv` reports `Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64`.
=> replace Processes::taskArray with a vector

basis/Posix.sml
Posix lseek was broken since it was using the call number for setfd.
=> Fix Posix lseek by using the correct dispatch call number.

config.h.in, configure.ac, libpolyml/elfexport.cpp
This has been tested in a Debian sid riscv64 chroot using qemu-user. The bundled libffi is too old to support RISC-V, so I patched it locally (and will be carrying a patch in the Debian packaging; it'd be nice if `--with-system-libffi` could have a way of not even configuring libffi, to avoid needing support for new architectures in the bundled libffi, as its configure script fails if building for an unknown architecture). There is a libffi 3.3-rc0 which could in theory be used to update the bundled libffi, but it's probably best to just wait until a proper release and require users/distributions to patch the embedded libffi like I am doing if they want to build for RISC-V.
=> Add support for RISC-V

mlsource/MLCompiler/CodeTree/X86Code/X86ICodeIdentifyReferences.ML
I think conflictState is not used in identifyreferences.
=> Remove unused code in X86ICodeIdentifyReferences

libpolyml/machoexport.cpp
mach-o/ppc/reloc.h is not present in Mac OS X version 10.15.
=> Remove unnecessary #include that breaks some builds

libpolyml/polyffi.cpp
Unix i386 uses FFI_SYSV, not FFI_UNIX64.
=> Fix libffi 3.3 build on Unix i386

basis/LargeWord.sml
Without IntInf as Int, conversion from int to large word is via word.
Word.wordSize < LargeWord.wordSize so conversion from word to large word
should sign extend.
=> Fix LargeWord.fromInt for negative arguments

basis/Foreign.sml, basis/ForeignConstants.sml, libpolyml/polyffi.cpp
This adds FFI conversions for the C types `size_t` and `ssize_t`, partially addressing #152.  The conversions use SML types `int` and `LargeInt.int` as for other conversions.  Conversions for other types mentioned in #152 could be added if this is the way to go.
I've check that this builds on Linux x86_64 and Darwin but not on Windows.
=> Add FFI conversions for C size types

libpolyml/sighandler.cpp
Fixes https://github.com/polyml/polyml/issues/155.  This patch has been tested on an x86_64 running Fedora Rawhide.
=> Adapt to nonconstant PTHREAD_STACK_MIN in glibc 2.34+

libpolyml/timing.cpp
The uninitialized fields were causing a segfault on Linux+glibc, when `Date.fmt s` was called and `s` contained `%Z` (or anything that expands to `%Z`, such as `%c` under some locales).
Fixes #189.
Note: I tried adding a test case, but unfortunately I could not reproduce this bug as part of the test suite.
My guess is that when running the test suite, the C stack expands to an area that only contains zeros instead of garbage data.
If the stack contains zeros, then the uninitialized `tm_zone` field would be a NULL pointer, which glibc would process correctly, instead of an invalid pointer which would cause the crash.
However, I have not verified this theory. I did verify that the patch fixes the issue, though.
=> Properly initialize unknown fields in `struct tm`.

Tests/Succeed/Test202.ML, basis/LargeWord.sml
Fixes the behavior where a word, if of size equal or larger than double the maximum integer representable, wrapped around instead of overflowing when converting to Int
=> Fix #200: Word.toInt not raising Overflow in some cases

basis/FinalPolyML.sml
`OS.Path.splitDirFile` returns `/` when called with `/`, so the `dir = ""` condition is never true if the file name is absolute. Combined with the dir being opened before the recursive call and only closed after the call has completed, this makes `reallyexists` loop infinitely until a SysErr is raised:
$ poly --eval 'PolyML.make "/"'
Poly/ML 5.9.1 Release
Exception- SysErr ("Too many open files", SOME EMFILE) raised
$
=> Fix PolyML.make infinite recursion when called with an absolute path.

Tests/Succeed/Test200.ML
`make tests` fails for Poly/ML built with `--enable-intinf-as-int=yes` or `--enable-compact32bit=yes` because `Test200.ML` assumes `Int.precision` is `SOME 63` in the tests of `IEEEReal.scan` with large exponents.  This commit should fix `Test200.ML` to work for any `Int.precision`.
=> Fix Test200.ML for when `Int.precision` is not `SOME 63`

polyc.in
Hi,
thanks again for fixing the macOS linker/exporter issue (7f548c30), but there's still the remaining issue in `polyc` script, where the generated `${LINK}` contains spaces and cannot be called as a valid execution. This PR fixes it by removing the surrounding double-quotes.
P. S. I hope a new minor release can be made after this fix, so that the prebuilt polyml packages on macOS (MacPorts and Homebrew, etc.) can be fixed by naturally moving to a new version. (Currently they are broken on recent macOS versions due the already fixed linker/exporter issue.) Having working prebuilt PolyML packages will greatly ease many potential users.
Regards,
Chun
=> Fix "polyc" when ${LINK} contains spaces

mlsource/MLCompiler/TYPE_TREE.ML
As far as I can tell, the branch is redundant (it is repeated twice).
=> remove redundant branch in TYPE_TREE
